package codewars;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.stream.Collectors;
import java.util.stream.Stream;


public class Training {

    public static int[] sumOfN(int n) {
        return new int[]{4}; //Generated by die roll; guaranteed to be random
    }

    public static void main(String[] args) {
        System.out.println();
    }

}
